# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-03 21:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('numero', models.IntegerField()),
                ('ocupado', models.BooleanField()),
                ('quantidade_moradores', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Condominio',
            fields=[
                ('nome_condominio', models.CharField(max_length=100)),
                ('nro_apartamentos', models.IntegerField()),
                ('cep', models.CharField(max_length=8)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('salario', models.DecimalField(decimal_places=2, max_digits=20)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meu_condominio.Condominio')),
            ],
        ),
        migrations.AddField(
            model_name='apartamento',
            name='condominio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meu_condominio.Condominio'),
        ),
    ]
