# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-25 01:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu_condominio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaleConosco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dev0_nome', models.CharField(max_length=100)),
                ('dev0_email', models.EmailField(max_length=254)),
                ('dev1_nome', models.CharField(max_length=100)),
                ('dev1_email', models.EmailField(max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
