# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-26 01:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meu_condominio', '0002_faleconosco'),
    ]

    operations = [
        migrations.CreateModel(
            name='DespesaExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=20)),
                ('motivo', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='faleconosco',
            name='dev0_email',
            field=models.EmailField(default='lucasjoao.lj@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='faleconosco',
            name='dev0_nome',
            field=models.CharField(default='Lucas Jo\xe3o Martins', max_length=100),
        ),
        migrations.AlterField(
            model_name='faleconosco',
            name='dev1_email',
            field=models.EmailField(default='w_mayk007@hotmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='faleconosco',
            name='dev1_nome',
            field=models.CharField(default='Wesley Mayk Gama Luz', max_length=100),
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('data', models.CharField(max_length=7)),
                ('agua', models.DecimalField(decimal_places=2, max_digits=20)),
                ('luz', models.DecimalField(decimal_places=2, max_digits=20)),
                ('gas', models.DecimalField(decimal_places=2, max_digits=20)),
                ('condominio_taxa', models.DecimalField(decimal_places=2, max_digits=20)),
                ('manutencoes', models.DecimalField(decimal_places=2, max_digits=20)),
                ('eh_geral', models.BooleanField()),
                ('despesa_extra', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='meu_condominio.DespesaExtra')),
                ('balanco', models.DecimalField(decimal_places=2, max_digits=20)),
                ('parcela', models.DecimalField(decimal_places=2, max_digits=20)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meu_condominio.Condominio')),
            ],
        ),
    ]
