# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-09 03:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meu_condominio', '0003_auto_20160830_0326'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cond',
            new_name='Condominio',
        ),
    ]
