# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-29 00:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('meu_condominio', '0004_auto_20161026_0146'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('dia', models.CharField(max_length=3)),
                ('turno', models.CharField(max_length=5)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('condominio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meu_condominio.Condominio')),
            ],
        ),
    ]
